---
- name: install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
      packages:
        - apache2
        - php7.3
        - ufw

#networking
- name: disable dhcp
  service:
      name: dhcpcd
      state: stopped
  become: true

- name: set static ip
  template:
      src: interfaces.j2
      dest: /etc/network/interfaces
  register: restart_networking
  become: true

- name: reboot if ip has changed
  reboot:
  when: restart_networking is changed
  become: true


#firewall
- name: Open ufw ports for ssh, http & https
  become: true
  shell: ufw allow OpenSSH && ufw allow http && ufw allow https

- name: Enable ufw
  become: true
  shell: ufw --force enable

#ssh
- name: Disable empty password login
  lineinfile: dest={{ server_sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
  notify: restart sshd
  become: true

- name: Disable remote root login
  lineinfile: dest={{ server_sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"
  notify: restart sshd
  become: true

- name: Disable password login
  lineinfile: dest={{ server_sshd_config }} regexp="^(#\s*)?PasswordAuthentication " line="PasswordAuthentication no"
  notify: restart sshd
  become: true


