sudo: required

language: bash

before_install:
  - sudo apt-get install -y ansible
addons:
  apt:
    update: true

services:
- docker

arch:
  packages:
  - ansible 
  script:
  - echo "start test on arch"
  - "mkdir -p /home/ljurk"
  - "sudo ansible-playbook -K playbook.yml -v"
  - echo "end test on arch"

script:
- "./tests/arch-travis.sh"
- echo "start test on ubuntu"
- "mkdir -p /home/ljurk"
- "sudo ansible-playbook -K playbook.yml -v"
- echo "end test on ubuntu"

