sudo: required

language: bash

services:
- docker

arch:
  script:
  - echo "hello from arch"
  - "./csvInstall.sh test"

script:
- echo "hello from outside"
- "./arch-travis.sh"
- echo "ciao from outside"
