sudo: required

language: bash

services:
- docker

arch:
  script:
  - echo "hello from arch"
  - "sudo pacman -S ansible"
  - "sudo ansible-playbook -K playbook.yml -v"

script:
- echo "hello from outside"
- "./tests/arch-travis.sh"
- echo "ciao from outside"
