sudo: required

language: bash

services:
- docker

arch:
  packages:
  # pacman packages
  - python
  - perl
  # aur packages
  - go-git
  # packages from papyros repo
  - papyros-shell
  - screenfetch-git
  script:
  - sudo screenfetch
  - "./csvInstall.sh"
  - echo "ciao from arch"

script:
- echo "hello from outside"
  #- "./csvInstall.sh"
