sudo: required

language: bash

services:
- docker

arch:
  packages:
  # pacman packages
  - python
  - perl
  # aur packages
  - go-git
  # packages from papyros repo
  - papyros-shell
  script:
  - "./csvInstall.sh"

script:
- "./csvInstall.sh"
