sudo: required

language: bash

before_install:
  - sudo apt-get install -y ansible
addons:
  apt:
    update: true

services:
- docker

arch:
  packages:
  - ansible 
  script:
  - echo "START test on arch"
  - "sudo mkdir -p /home/ljurk"
  - "sudo ansible-playbook playbook.yml -i hosts -v"
  - echo "END test on arch"

script:
- "./tests/arch-travis.sh"

