---
- hosts: vagrant
  vars:
    - dotfiles_path: "{{ ansible_env.HOME }}/.dot"
    - dotfiles_url: "https://github.com/ljurk/dot.git"
    - scripts_path: "{{ ansible_env.HOME }}/.scripts"
    - scripts_url: "git@github.com:ljurk/scripts.git"
    - id_rsa: "~/.ssh/id_rsa"
    - id_rsa_pub: "~/.ssh/id_rsa.pub"
    - all_users:
        - user: ljurk
          homedir: /home/ljurk
  roles: 
     - update
     - prgDefault
     - ssh
     - powerline-fonts
     - dotfiles
     - idm2cn

