---
- hosts: all
  vars:
    homedir: /home/ljurk
    user: ljurk
    dotfiles_path: "{{ homedir }}/.dot"
    dotfiles_url: "https://github.com/ljurk/dot.git"
    scripts_path: "{{ homedir }}/.scripts"
    scripts_url: "https://github.com/ljurk/scripts.git"
    #website
    website_domain_name: 303v.cf
    website_server_admin_email: ljurk@pm.me
    #certbot
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_hour: 3
    certbot_auto_renew_minute: 30
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: ljurk@pm.me
    certbot_certs:
      - domains:
          - 303v.cf
    certbot_create_standalone_stop_services:
      - apache2
    #vpn
    openvpn_server_name: 303v.cf
    openvpn_download_dir: /home/ljurk/projects/init/transport
    openvpn_install_dir: /opt/openvpn
    openvpn_client_name: ljurk
    openvpn_ca_email: ljurk@pm.me
  roles:
    - update
    - prgDefault
    - prgServer
    - dotfiles
    - certbot
    - website
    - openvpn


