---
- name: Clone dotfiles into ~/dotfiles
  vars:
    dotfiles_path: /home/ljurk/yoyo/dotfiles2
  tasks:
    - name: clone
      git:
        repo: https://github.com/ljurk/dotfiles.git
        version: master
        dest: "{{ dotfiles_path }}"
        accept_hostkey: yes

    - name: Stow configurations
      shell: stow *
      args:
        chdir: "{{ dotfiles_path }}"
