---
- hosts: localhost
  vars:
    - dotfiles_path: "{{ ansible_env.HOME }}/.dot"
    - dotfiles_url: "https://github.com/ljurk/dot.git"
    - scripts_path: "{{ ansible_env.HOME }}/.scripts"
    - scripts_url: "https://github.com/ljurk/scripts.git"
  roles:
    - update
    - prgDefault
    - prgClient
    - i3
    - dotfiles
