---
- hosts: rpi
  vars:
    - dotfiles_path: "{{ ansible_env.HOME }}/.dot"
    - dotfiles_url: "https://github.com/ljurk/dot.git"
    - scripts_path: "{{ ansible_env.HOME }}/.scripts"
    - scripts_url: "https://github.com/ljurk/scripts.git"
    - staticIp_ipaddress: 192.168.0.21/24
  roles:
    - staticIp
    - update
    - prgDefault
    - dotfiles
