#!/bin/sh

docs="/home/ljurk/projects/mk/docs/roles"

for D in `find .  -mindepth 1 -maxdepth 1 -type d |sed 's#\.\/##g' `
do
    src="./$D/tasks/main.yml"
    output="$D.md"
    echo '~~~~' | cat - $src > temp && mv temp $output
    echo '~~~~' >> $output
    docspath="$docs/$output"
    real=$(realpath $output)
    ln -s $real $docspath
    echo "link $output to $docspath"
done


