---
# Author: Lukn
# Description: installs dotfiles specified in the given url
- name: install stow
  package:
    name: stow
    state: present
  become: true

- name: delete default dotfiles
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  with_items:
    - .dot
    - .bashrc
    - .bash_profile
    - .profile
    - .Xresources
    - .xinitrc
    - .config/i3/config
    - .vimrc
    - .zshrc
    - .gtkrc-2.0
    - .dmenurc
    - .config/autorandr
    - .config/gtk-3.0
    - .config/i3blocks
    - .config/termite
    - .config/dunst
    - .config/ranger

- name: "clone dotfiles {{ dotfiles_path }}"
  git:
    repo: "{{ dotfiles_url }}"
    version: master
    dest: "{{ dotfiles_path }}"
    accept_hostkey: true

- name: "delete readme.md"
  file:
    path: "{{ dotfiles_path }}/{{ item }}"
    state: absent
  with_items:
    - _config.yml
    - readme.md

- name: Stow configurations
  shell: stow *
  args:
    chdir: "{{ dotfiles_path }}"

- name: change antigen path
  replace:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: "^source /usr/share/zsh/share/antigen.zsh$"
    replace: "source /usr/share/zsh-antigen/antigen.zsh"
  tags: replace
  when: ansible_distribution == 'Debian'
