---
- name: "clone dotfiles {{ dotfiles_path }}"
  git:
    repo: "{{ dotfiles_url }}"
    version: master
    dest: "{{ dotfiles_path }}"
    accept_hostkey: yes

- name: Stow configurations
  shell: stow *
  args:
    chdir: "{{ dotfiles_path }}"
