---
# Author: Lukn
# Description: installs dotfiles specified in the given url
- name: delete default dotfiles
  file:
      path: "{{ homedir }}/{{ item }}"
      state: absent
  with_items:
      - .dot
      - .bashrc
      - .bash_profile
      - .Xresources
      - .config/i3/config

- name: "clone dotfiles {{ dotfiles_path }}"
  git:
    repo: "{{ dotfiles_url }}"
    version: master
    dest: "{{ dotfiles_path }}"
    accept_hostkey: yes

- name: Stow configurations
  shell: stow *
  args:
    chdir: "{{ dotfiles_path }}"
