---
# Author: Lukn
# Description: installs dotfiles specified in the given url
- name: delete default dotfiles
  file:
      path: "{{ ansible_env.HOME }}/{{ item }}"
      state: absent
  with_items:
      - .dot
      - .bashrc
      - .bash_profile
      - .Xresources
      - .config/i3/config
      - .vimrc
      - .zshrc
      - .config/autorandr
      - .config/gtk-3.0
      - .config/i3blocks
      - .config/termite
      - .config/dunst
      - .config/ranger


- name: "clone dotfiles {{ dotfiles_path }}"
  git:
    repo: "{{ dotfiles_url }}"
    version: master
    dest: "{{ dotfiles_path }}"
    accept_hostkey: yes

- name: "clone dotfiles {{ dotfiles_path }}"
  file:
    path: "{{ dotfiles_path }}/readme.md"
    state: absent

- name: Stow configurations
  shell: stow *
  args:
    chdir: "{{ dotfiles_path }}"
