---
- name: check if .ssh dir exist
  file:
      path: "{{ item.homedir }}/.ssh"
      state: directory
      mode: 0700
      owner: "{{ item.user }}"
      group: "{{ item.user }}"
  with_items: "{{ all_users }}"
  become: true

- name: copy private ssh key to host
  copy:
      src: "{{ id_rsa }}"
      dest: "{{ item.homedir }}/.ssh/id_rsa"
      mode: 0600
      owner: "{{ item.user }}"
      group: "{{ item.user }}"
  with_items: "{{ all_users }}"
  become: true

- name: copy public ssh key to host
  copy:
      src: "{{ id_rsa_pub }}"
      dest: "{{ item.homedir }}/.ssh/id_rsa.pub"
      owner: "{{ item.user }}"
      group: "{{ item.user }}"
      mode: 0644
  with_items: "{{ all_users }}"
  become: true

- name: copy public ssh key to authorized_keys
  copy:
      src: "{{ id_rsa_pub }}"
      dest: "{{ item.homedir }}/.ssh/authorized_keys"
      owner: "{{ item.user }}"
      group: "{{ item.user }}"
      mode: 0644
  with_items: "{{ all_users }}"
  become: true
