---
- name: install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
      packages:
        # tools
        - pandoc
        - git
        - vim
        - wget
        - python3.7
        - python-pip
        - python3-pip
        - zsh
        - stow
        - ruby
        - tmux

# setup zsh
- name: setup zsh
  include_role:
      name: zsh

- name: Install pip 3.7 packages
  pip:
      name:
          - powerline-status
      extra_args: --user
      executable: pip3
  tags: pip

- name: "clone scripts {{ scripts_path }}"
  git:
    repo: "{{ scripts_url }}"
    version: master
    dest: "{{ scripts_path }}"
    accept_hostkey: yes
