---
# setup zsh
- name: create .antigen dir
  file:
      path: "{{ ansible_env.HOME }}/.antigen"
      state: directory

- name: install zsh package
  package:
      name: "zsh"
  become: true

- name: install antigen packages
  package:
      name: "zsh-antigen"
  become: true
  when: ansible_distribution == 'Debian'

- name: install aur packages
  aur:
      name: "antigen"
  become: true
  when: ansible_distribution == 'Arch'

- name: change shell to zsh
  become: true
  user:
      name: "{{ ansible_env.USER }}"
      shell: /usr/bin/zsh
      state: present
