---
# setup zsh
- name: create .antigen dir
  file:
      path: "{{ ansible_env.HOME }}/.antigen"
      state: directory

- name: install aur packages
  aur:
      name: "antigen"
      skip_installed: true

- name: change shell to zsh
  become: true
  user:
      name: "{{ ansible_env.USER }}"
      shell: /usr/bin/zsh
      state: present
