---
- name: Install Certbot.
  package:
    name: "{{ certbot_package }}"
    state: present
  become: true


- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
