---
- name: install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      # dependency for makepkg
      - binutils
      - fakeroot
      # other build tools
      - cmake
      # tools
      - termite
      - texlive-core
      - texlive-fontsextra
      - zathura-pdf-mupdf
      - pandoc
      - blueman #blueetooth manager
      - gnupg
      - ranger
      - rsync
      - screenfetch
      - shellcheck
      - networkmanager
      - acpi
      - bat
      - ansible
      - docker
      - vagrant
      - virtualbox
      # audio
      - pulseaudio-alsa
      - pulseaudio-jack
      - alsa-utils
      - alsa-firmware
      - alsa-plugins
      # gtk
      - gtk2
      - gtk3
      - adapta-gtk-theme
      - papirus-icon-theme
      # gui tools
      - rofi
      - firefox
      - remmina
      - freerdp
      - thunderbird
      - cadence
      - audacity
      - pavucontrol
      - zathura
      - gimp
      - gparted
      - gsmartcontrol # monitors drives
      - libreoffice-fresh
      - pcmanfm
      # networking
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
      - networkmanager-pptp
      - networkmanager-vpnc
      - nmap
      - xfce4-power-manager
      - xorg-xrandr
      - arandr
      - autorandr
      - lightdm
      - lightdm-gtk-greeter

- name: activate networkmanager
  systemd:
      name: "{{ item }}"
      enabled: yes
  with_items:
        - lightdm
        - NetworkManager
        - autorandr

- name: set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: yes
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec nm-applet"

# install this module first: https://github.com/kewlfft/ansible-aur
- name: install aur packages
  aur:
    name: "{{ packages }}"
    skip_installed: true
  vars:
      packages:
        - ttf-font-awesome-4
        - networkmanager-dmenu-git
        - xcursor-breeze
        #dependency for keepmenu
        - python-pyuserinput-git
        #and keepmenu itself
        - python-keepmenu-git

#setup vpn
- name: create cert dir
  file:
    path: "{{ ansible_env.HOME }}/cert"
    state: directory

- name: copy vpn stuff
  template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/cert"
  with_items:
    - TUD.vpn
    - TUD-CA.pem

