---
- name: install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
      packages:
        # tools
        - termite
        - texlive-core
        - texlive-fontsextra
        - zathura-pdf-mupdf
        - pulseaudio-alsa
        - pulseaudio-jack
        - networkmanager
        # gtk
        - gtk2
        - gtk3
        - adapta-gtk-theme
        - papirus-icon-theme
        # gui tools
        - firefox
        - remmina
        - freerdp
        - thunderbird
        - cadence
        - pavucontrol
        - zathura
        - pcmanfm
        - nm-applet

- name: activate networkmanager
  systemd:
      name: NetworkManager
      state: started
      enabled: yes

- name: set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: yes
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec nm-applet"

# install this module first: https://github.com/kewlfft/ansible-aur
- name: install aur packages
  aur:
    name: "{{ packages }}"
    skip_installed: true
  vars:
      packages:
        - ttf-font-awesome-4
        - networkmanager-dmenu-git
        - xcursor-breeze

