---
- name: install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
      packages:
        # dependency for makepkg
        - binutils
        - fakeroot
        # tools
        - pandoc
        - git
        - vim
        - rxvt-unicode
        - wget
        - python
        - python-pip
        - zsh
        - texlive-core
        - texlive-fontsextra
        - zathura-pdf-mupdf
        - stow
        - docker
        - ruby
        - pulseaudio-alsa
        - pulseaudio-jack
        - tmux
        # gui tools
        - firefox
        - remmina
        - freerdp
        - thunderbird
        - cadence
        - pavucontrol
        - zathura
        - pcmanfm

# install this module first: https://github.com/kewlfft/ansible-aur
- name: install aur packages
  aur:
    name: "{{ packages }}"
    skip_installed: true
  vars:
      packages:
        - ttf-font-awesome-4
        - networkmanager-dmenu-git

# setup zsh
- name: setup zsh
  include_role:
      name: zsh

- name: Install pip 3.7 packages
  pip:
      name:
        - keepmenu
        - powerline-status
      extra_args: --user

- name: "clone scripts {{ scripts_path }}"
  git:
    repo: "{{ scripts_url }}"
    version: master
    dest: "{{ scripts_path }}"
    accept_hostkey: yes
