---
- name: install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      # dependency for makepkg
      - binutils
      - fakeroot
      # other build tools
      - cmake
      ## tools
      # pdf
      - pandoc
      - termite
      - texlive-core
      - texlive-fontsextra
      - zathura
      - zathura-pdf-mupdf
      # environment
      - gnupg
      - rsync
      - networkmanager
      - acpi
      - xfce4-power-manager
      - gsmartcontrol  # monitors drives
      # cli tools
      - shellcheck
      - bat
      # virtualization & provisioning
      - docker
      - ansible
      - vagrant
      - virtualbox
      # audio
      - pulseaudio-alsa
      - pulseaudio-jack
      - alsa-utils
      - alsa-firmware
      - alsa-plugins
      - cadence
      - audacity
      - pavucontrol
      # basic
      - rofi
      - firefox
      - thunderbird
      # work
      - remmina
      - freerdp
      # file system
      - gparted
      - thunar
      - nextcloud-client
      # graphical
      - blueman  # blueetooth manager
      - gimp
      - lxappearance
      # networking
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
      - networkmanager-pptp
      - networkmanager-vpnc
      - nmap
      # display
      - xorg-xrandr
      - arandr
      - autorandr
      - gtk2
      - gtk3
      - adapta-gtk-theme
      - papirus-icon-theme
      - ttf-dejavu

- name: activate networkmanager
  systemd:
    name: "{{ item }}"
    enabled: true
  with_items:
    - NetworkManager
    - autorandr

- name: set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: true
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec nm-applet"

# install this module first: https://github.com/kewlfft/ansible-aur
- name: install aur packages
  aur:
    name: "{{ packages }}"
    skip_installed: true
  vars:
    packages:
      - ttf-font-awesome-4
      - networkmanager-dmenu-git
      - xcursor-breeze
      # dependency for keepmenu
      - python-pyuserinput-git
      # and keepmenu itself
      - python-keepmenu-git

# setup vpn
- name: create cert dir
  file:
    path: "{{ ansible_env.HOME }}/cert"
    state: directory

- name: copy vpn stuff
  template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/cert"
  with_items:
    - TUD.vpn
    - TUD-CA.pem
