---
- name: install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
      packages:
        # tools
        - termite
        - texlive-core
        - texlive-fontsextra
        - zathura-pdf-mupdf
        - pulseaudio-alsa
        - pulseaudio-jack
        - gtk2
        - gtk3
        - adapta-gtk-theme
        - papirus-icon-theme
        # gui tools
        - firefox
        - remmina
        - freerdp
        - thunderbird
        - cadence
        - pavucontrol
        - zathura
        - pcmanfm

# install this module first: https://github.com/kewlfft/ansible-aur
- name: install aur packages
  aur:
    name: "{{ packages }}"
    skip_installed: true
  vars:
      packages:
        - ttf-font-awesome-4
        - networkmanager-dmenu-git
        - xcursor-breeze

