---
- name: install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
      packages:
        - pandoc
        - git
        - wget
        - python
        - python2
        - python-pip
        - python2-pip
        - i3blocks
        - zsh
        - firefox
        - remmina
        - freerdp
        - thunderbird
        - cadence
        - pavucontrol
        - pandoc
        - texlive-core
        - texlive-fontsextra
        - zathura
        - zathura-pdf-mupdf
        - ttf-font-awesome
        - stow
        - docker
        - ruby
        - pulseaudio-alsa
        - pulseaudio-jack

# setup zsh
- name: setup zsh
  include_role:
      name: zsh

- name: Install pip 3.7 packages
  pip:
      name:
        - keepmenu
        - powerline-status
      extra_args: --user

- name: Install pip 2.7 packages
  pip:
      name:
        - platformio
      executable: pip2.7
      extra_args: --user
